class CampagnJsons:
    DEFAULT = {
        "name": None,
        "read_only": False,
        "conversion_funnel_id": None,
        "objective": "reach",
        "enable_offline_goals": False,
        "targetings": {
            "split_audience": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10
            ],
            "sex": [
                "male",
                "female"
            ],
            "age": {
                "age_list": [
                    0,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23,
                    24,
                    25,
                    26,
                    27,
                    28,
                    29,
                    30,
                    31,
                    32,
                    33,
                    34,
                    35,
                    36,
                    37,
                    38,
                    39,
                    40,
                    41,
                    42,
                    43,
                    44,
                    45,
                    46,
                    47,
                    48,
                    49,
                    50,
                    51,
                    52,
                    53,
                    54,
                    55,
                    56,
                    57,
                    58,
                    59,
                    60,
                    61,
                    62,
                    63,
                    64,
                    65,
                    66,
                    67,
                    68,
                    69,
                    70,
                    71,
                    72,
                    73,
                    74,
                    75
                ],
                "expand": True
            },
            "geo": {
                "regions": [
                    188
                ]
            },
            "interests_soc_dem": [],
            "segments": [],
            "interests": [],
            "fulltime": {
                "flags": [
                    "cross_timezone",
                    "use_holidays_moving"
                ],
                "fri": [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23
                ],
                "mon": [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23
                ],
                "sat": [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23
                ],
                "sun": [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23
                ],
                "thu": [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23
                ],
                "tue": [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23
                ],
                "wed": [
                    0,
                    1,
                    2,
                    3,
                    4,
                    5,
                    6,
                    7,
                    8,
                    9,
                    10,
                    11,
                    12,
                    13,
                    14,
                    15,
                    16,
                    17,
                    18,
                    19,
                    20,
                    21,
                    22,
                    23
                ]
            },
            "pads": [
                102646,
                102650,
                102651,
                102655,
                102656
            ],
            "mobile_types": [
                "tablets",
                "smartphones"
            ],
            "mobile_vendors": [],
            "mobile_operators": []
        },
        "age_restrictions": None,
        "date_start": "2022-01-01",
        "date_end": "2022-01-07",
        "autobidding_mode": "max_shows",
        "uniq_shows_period": "day",
        "uniq_shows_limit": None,
        "banner_uniq_shows_limit": None,
        "budget_limit_day": "100",
        "budget_limit": None,
        "mixing": "recommended",
        "utm": None,
        "enable_utm": True,
        "price": "1",
        "max_price": "0",
        "package_id": 1030,
        "banners": [
            {
                "urls": {
                    "primary": {
                        "id": 55214326
                    }
                },
                "textblocks": {
                    "title_25": {
                        "text": "Cmpg caption"
                    },
                    "text_90": {
                        "text": "Lorem ipsum"
                    },
                    "cta_sites_full": {
                        "text": "visitSite"
                    }
                },
                "content": {
                    "image_90x75": {
                        "id": 9640583
                    }
                },
                "name": ""
            }
        ]
    }
